version = 0.1
[default.deploy.parameters]
stack_name = "learning-lambda-fastapi"
s3_prefix = "learning-lambda-fastapi"
region = "ap-northeast-1"
capabilities = "CAPABILITY_IAM"
resolve_s3 = true
resolve_image_repos = true
