version = 0.1
[default.deploy.parameters]
stack_name = "simple-fastapi-on-lambda"
s3_prefix = "simple-fastapi-on-lambda"
region = "ap-northeast-1"
capabilities = "CAPABILITY_IAM"
resolve_s3 = true
resolve_image_repos = true
