AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  sam-handson

  Sample SAM Template for sam-handson

Globals:
  Function:
    Timeout: 10
    MemorySize: 128

Resources:
  GetFunction:
    Type: AWS::Serverless::Function
    Properties:
      PackageType: Image
      Events:
        HelloWorld:
          Type: Api
          Properties:
            Path: /
            Method: GET
    Metadata:
      DockerContext: ./hello_world
      Dockerfile: Dockerfile
  PostFunction:
    Type: AWS::Serverless::Function
    Properties:
      PackageType: Image
      Events:
        HelloWorld:
          Type: Api
          Properties:
            Path: /
            Method: POST
    Metadata:
      DockerContext: ./hello_world
      Dockerfile: Dockerfile
  PutFunction:
    Type: AWS::Serverless::Function
    Properties:
      PackageType: Image
      Events:
        HelloWorld:
          Type: Api
          Properties:
            Path: /
            Method: PUT
    Metadata:
      DockerContext: ./hello_world
      Dockerfile: Dockerfile
  DeleteFunction:
    Type: AWS::Serverless::Function
    Properties:
      PackageType: Image
      Events:
        HelloWorld:
          Type: Api
          Properties:
            Path: /
            Method: DELETE
    Metadata:
      DockerContext: ./hello_world
      Dockerfile: Dockerfile
