AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  sam-handson

  Sample SAM Template for sam-handson

Globals:
  Function:
    Timeout: 10
    MemorySize: 128

Resources:
  GetFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub ${AWS::StackName}-get
      Description: "GETメソッド。"
      PackageType: Image
      Events:
        HelloWorld:
          Type: Api
          Properties:
            Path: /
            Method: GET
    Metadata:
      DockerContext: ./src
      Dockerfile: Dockerfile
  PostFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub ${AWS::StackName}-post
      Description: "POSTメソッド。"
      PackageType: Image
      Events:
        HelloWorld:
          Type: Api
          Properties:
            Path: /
            Method: POST
    Metadata:
      DockerContext: ./src
      Dockerfile: Dockerfile
  PutFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub ${AWS::StackName}-put
      Description: "PUTメソッド。"
      PackageType: Image
      Events:
        HelloWorld:
          Type: Api
          Properties:
            Path: /
            Method: PUT
    Metadata:
      DockerContext: ./src
      Dockerfile: Dockerfile
  DeleteFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub ${AWS::StackName}-delete
      Description: "DELETEメソッド。"
      PackageType: Image
      Events:
        HelloWorld:
          Type: Api
          Properties:
            Path: /
            Method: DELETE
    Metadata:
      DockerContext: ./src
      Dockerfile: Dockerfile
