name: Test

on:
  push:
    branches:
      - main
      - develop
      - 'issue/*'
  pull_request:
    branches:
      - main
      - develop
      - 'issue/*'

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.9', '3.10']
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Use Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install pip
        run: python -m pip install --upgrade pip
      - name: Install dependencies
        run: pip install -r ./tests/requirements.txt
      - name: Run tests
        run: pytest
